version: 2
updates:
  # 监控 Node-RED Dockerfile 的基础镜像版本 (hassio-addons/base)
  - package-ecosystem: docker
    directory: /node-red
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  # 监控 GitHub Actions 依赖版本
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
