version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/node-red"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    target-branch: "main"
    # 优先更新补丁和次要版本，主版本更新需要手动确认
    versioning-strategy: increase
    commit-message:
      prefix: "deps"
      include: "scope"
    # 自动合并安全更新和非破坏性更新
    auto-merge:
      enabled: true
      types:
        - "patch"
        - "minor"
    # 忽略特定依赖或版本（根据你的需求调整）
    #ignore:
      # 示例：如果不想更新node-red到5.x版本
    #  - dependency-name: "node-red"
    #    versions: [">=16"]
      # 示例：保持bcryptjs在3.x版本
    #  - dependency-name: "bcryptjs"
    #    versions: ["4.x"]
    # 为PR添加标签，方便筛选
    labels:
      - "dependencies"
      - "automated"
    # 每次更新创建单独的PR，而不是合并多个更新
    open-pull-requests-limit: 10
