# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: NeteaseCloudMusicApi
version: "0.0.1"
slug: CloudMusicApi 
description: NeteaseCloudMusicApi
url: "https://github.com/shiqixixixi/hassio-addons/tree/main/example"
startup: "application"
boot: "auto"
image: "binaryify/netease_cloud_music_api"
init: false
map:
  - share:rw
options: 
  - local_scan:true
  - options:[]
webui: "http://[HOST]:[PORT:3200]"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386