name: ntfy
version: "latest"
slug: ntfy
description: ntfy
url: "https://github.com/binwiederhier/ntfy"
arch:
  - amd64
startup: application
boot: auto
ports:
  80/tcp: 8800
ports_description:
  80/tcp: ntfy server port
