name: alist
version: 3.19.0
slug: alist
description: alist
url: https://github.com/alist-org/alist
codenotary: alist
startup: services
ingress: true
ingress_port: 5244
ingress_stream: true
init: false
panel_icon: mdi:pipe
panel_title: alist
arch:
  - aarch64
  - amd64
map:
  - config
host_network: true
ports: 
  - 8080/tcp: 8080
ports_description:
  - 8080/tcp: "Web interface"
homeassistant_api: false
auth_api: false
docker_api: false
host_dbus: false
apparmor: true