name: alist
version: 3.19.0
slug: alist
description: alist
url: https://github.com/alist-org/alist
codenotary: alist
startup: services
ingress: true
ingress_port: 5244
ingress_stream: true
init: false
panel_icon: mdi:pipe
panel_title: alist
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config
host_network: true
ports: 
  5244/tcp: 5244
ports_description:
  5244/tcp: "Web interface"
webui: http://[HOST]:[PORT:5244]
homeassistant_api: false
auth_api: false
docker_api: false
host_dbus: false
apparmor: true