version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/deploy"
    schedule:
      interval: daily
      time: "09:00"
