name: PushDeer
version: 2.0
slug: pushdeer_server
description: PushDeer
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
url: https://github.com/easychen/pushdeer
host_network: false
options:
  mqtt: {}
schema:
  mqtt:
    server: str?
    ca: str?
    key: str?
    cert: str?
    user: str?
    password: str?
ports:
  '80/tcp': 8800
ports_description:
  '80/tcp': Web interface
panel_icon: mdi:earth
panel_title: PushDeer
panel_admin: false
hassio_api: true
hassio_role: manager
webui: http://[HOST]:[PORT:8800]
homeassistant_api: true
ingress: true
auth_api: false
docker_api: false
host_dbus: false
apparmor: true
ingress_port: 80
ingress_entry: ''