name: Redis
version: "7.0.15"
slug: redis
description: redis
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
url: https://github.com/shiqixixixi/hassio-addons
host_network: true
options:
  ALLOW_EMPTY_PASSWORD: true
  password: null
schema:
  ALLOW_EMPTY_PASSWORD: bool
  password: str
ports:
  "6379/tcp": 6379
ports_description:
  "6379/tcp": Web interface
panel_icon: mdi:earth
panel_title: Redis
hassio_role: manager
homeassistant_api: true
apparmor: true
ingress_port: 6379
