ARG BUILD_FROM
FROM $BUILD_FROM
ENV ALLOW_EMPTY_PASSWORD yes 
#CMD ["redis-cli","ping"]


#FROM bitnami/redis

#ENV ALLOW_EMPTY_PASSWORD yes 
#COPY redis.conf /usr/local/etc/redis/redis.conf
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#CMD ["CMD", "redis-cli","ping"]