daemonize no
pidfile /var/run/redis/redis.pid
port 6379
bind 0.0.0.0
timeout 0
tcp-keepalive 300
# 移除或注释掉硬编码的dir，由命令行参数动态指定
# dir /data/redis
dbfilename dump.rdb
appendonly no
maxmemory 128mb
maxmemory-policy allkeys-lru
protected-mode no