daemonize no
pidfile /var/run/redis/redis.pid
port 6379
bind 0.0.0.0
timeout 0
tcp-keepalive 300
dir /data/redis
dbfilename dump.rdb
appendonly no
appendfilename "appendonly.aof"
maxmemory 128mb  # 默认值，后续会动态修改
maxmemory-policy allkeys-lru
protected-mode no