name: Build And Push
on:
  push:
    tags:        
      - '*' 
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Environment Variable
        id: vars
        run: echo "::set-output name=build_version::$(git describe --tags)"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/Dockerfile
          platforms:  |
            linux/arm
            linux/arm64
            linux/amd64
          tags: |
            adams549659584/bark-server:latest
            adams549659584/bark-server:${{ steps.vars.outputs.build_version }}
          push: true
          cache-from: type=registry,ref=${{ github.repository }}:cache
          cache-to: type=registry,ref=${{ github.repository }}:cache,mode=max          
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
